# ANSIBLE ENV
ansible_connection: ssh
ansible_user: ubuntu
ansible_ssh_pass: 4esz3wa2q1
ansible_sudo_pass: 4esz3wa2q1
ansible_ssh_private_key_file: files/sgnd.pem
ansible_python_interpreter: /usr/bin/python3

# SSH ENV
pass_auth: PasswordAuthentication yes
pubkey_auth: PubkeyAuthentication yes

# FIREWALL ENV
http_port: 80
https_port: 443
disable_default: true

# SWAP ENV
swap_file_path: /swapfile
# Use any of the following suffixes
# c=1
# w=2
# b=512
# kB=1000
# K=1024
# MB=1000*1000
# M=1024*1024
# xM=M
# GB=1000*1000*1000
# G=1024*1024*1024
swap_file_size: 1024
swappiness: 1

# DOCKER ENV
docker_apt_release_channel: stable
docker_apt_arch: amd64
docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
docker_apt_gpg_key: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
docker_compose_version: "1.28.5"

# PHP ENV
php_sourcelist_path: "/etc/apt/sources.list.d/ppa_ondrej_php_{{ansible_distribution_release}}.list"

# MONITORING ENV
monitoring_url : "https://github.com/prometheus/node_exporter/releases/download/v1.2.2/node_exporter-1.2.2.linux-amd64.tar.gz"

# CREATE DEFAULT USER ENV
default_username: cmsmanajer
default_password: $6$AQVuJekcMoVQgfa8$9yRYYe2P0R59g7wGAGs4FR.iWE3O.tfBEGtOpx0CKAoU8oISlLHa7hWfirFQC/ItjnzzBMMwAGA5O.Ze3TjLA/
# mkpasswd --method=sha-512 : AQVuJekcMoVQgfa8

# CREATE USER ENV
username: 
password: 
# mkpasswd --method=sha-512 :

# MYSQL ENV
mysql_root_username: root
mysql_root_password: root

# DATABASE ENV
app_username: yes
app_password: yes
app_database: yes

# WEB SERVER ENV (APACHE / NGINX)
app_domain: yes.cmsmanajer.com
app_config: yes.cmsmanajer.com.conf

# CMS WORDPRESS ENV
app_dbprefix: wpx_
wordpress_home_url: http://yes.cmsmanajer.com
wordpress_site_title: CMS Manajer
wordpress_admin_user: cmsmanajer
wordpress_admin_user_pass: cmsmanajer
wordpress_admin_email: email@example.com