# ssh
ansible_connection: ssh
ansible_user: ubuntu
ansible_ssh_pass: 4esz3wa2q1
ansible_sudo_pass: 4esz3wa2q1
ansible_ssh_private_key_file: files/sgnd.pem
ansible_python_interpreter: /usr/bin/python3

# users
pass_auth: PasswordAuthentication yes
pubkey_auth: PubkeyAuthentication yes

# certbot
certbot_repository: "ppa:certbot/certbot"