---
- name: "backup /etc/security/limits.conf"
  shell: cp /etc/security/limits.conf /etc/security/limits.conf.backup
  args:
    executable: /bin/bash
  tags:
    - connect-server

- name: "copy ulimits config to /etc/security/limits.conf"
  copy: 
    src: "{{ item }}"
    dest: /etc/security
  with_items:
    - limits.conf
  tags:
    - connect-server