- hosts: all
  become: true
  gather_facts: no
  roles:
    - cman-app-apache
    - cman-app-nginx
    - cman-app-mysql
    - cman-app-php
    - cman-cms-wordpress
  handlers:
  - name: Reload Apache
    service:
      name: apache2
      state: reloaded
  - name: Restart Apache
    service:
      name: apache2
      state: restarted
  - name: Reload Nginx
    service:
      name: nginx
      state: reloaded
  - name: Restart Nginx
    service:
      name: nginx
      state: restarted