- hosts: all
  become: true
  gather_facts: yes
  
  roles:
    - sys-optimiz
    - sys-users
    - sys-db
    - env-amn
    - env-amp
    - env-ampy
    - env-emn
    - env-emp
    - env-empy
    - app-wordpress

  handlers:
  - name: start-apache
    service:
      name: apache2
      state: started

  - name: reload-apache
    service:
      name: apache2
      state: reloaded

  - name: restart-apache
    service:
      name: apache2
      state: restarted

  - name: start-nginx
    service:
      name: nginx
      state: started

  - name: reload-nginx
    service:
      name: nginx
      state: reloaded

  - name: restart-nginx
    service:
      name: nginx
      state: restarted

  - name: autoremove
    apt:
      autoremove: yes
