- hosts: all
  become: true
  gather_facts: no
  roles:
    - lamp-app
  handlers:
  - name: Reload Apache
    service:
      name: apache2
      state: reloaded

  - name: Restart Apache
    service:
      name: apache2
      state: restarted
