- hosts: all
  become: true
  gather_facts: no
  roles:
    - lemp-app
  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted