---
- name: "install apache"
  apt: name={{ item }}
  loop:
    - apache2
  tags:
    - apache

- name: "create folder {{ app_domain }}"
  stat:
    path: "/var/www/{{ app_domain }}"
  register: appdomain
  tags:
    - apache
    - create-app-apache

- name: "directory is already existed"
  debug:
    msg: "directory is already existed"
  when: appdomain.stat.exists
  tags:
    - apache
    - create-app-apache

- name: "create folder {{ app_domain }}"
  file:
    path: "/var/www/{{ app_domain }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
  when: appdomain.stat.exists == false
  tags:
    - apache
    - create-app-apache

- name: "set up apache virtualhost"
  template:
    src: "files/{{ item }}"
    dest: "/etc/apache2/sites-available/{{ app_config }}"
  with_items:
    - apache.conf.j2
  notify: Reload Apache
  tags:
    - apache
    - create-app-apache

- name: "copy index.html"
  copy: 
    src: "{{ item }}"
    dest: "/var/www/{{ app_domain }}"
  with_items:
    - index.html
  tags:
    - apache
    - create-app-apache

- name: "enable new site"
  shell: /usr/sbin/a2ensite {{ app_config }}
  notify: Reload Apache
  tags:
    - apache
    - create-app-apache

- name: "disable default apache site"
  shell: /usr/sbin/a2dissite 000-default.conf
  when: disable_default
  notify: Reload Apache
  tags:
    - apache

## Cleanup
- name: "Running command : check directory"
  stat:
    path: /var/www/{{ app_domain }}
  register: app_dir
  tags:
    - delete-app-apache

- name: "Running command : delete directory"
  command: "rm -fr /var/www/{{ app_domain }}"
  when: app_dir.stat.exists
  tags:
    - delete-app-apache

- name: "Running message : if directory doesn't exist"
  debug:
    msg: "directory is doesn't exist"
  when: app_dir.stat.exists == false
  tags:
    - delete-app-apache

- name: "Running command : disable apache site"
  shell: "/usr/sbin/a2dissite {{ app_config }}"
  notify: Reload Apache
  tags:
    - delete-app-apache

- name: "Running command : check directory"
  stat:
    path: /etc/apache2/sites-available/{{ app_config }}"
  register: app_apache_available
  tags:
    - delete-app-apache

- name: "Running command : delete site"
  command: "rm /etc/apache2/sites-available/{{ app_config }}"
  notify: Reload Apache
  when: app_apache_available.stat.exists
  tags:
    - delete-app-apache

- name: "Running message : if site-available doesn't exist"
  debug:
    msg: "directory is doesn't exist"
  when: app_apache_available.stat.exists == false
  tags:
    - delete-app-apache

# Cleanup
- name: "Running command : uninstall LAMP"
  apt: name={{ item }} status=absent
  loop:
    - apache2
    - mysql-server
    - python3-pymysql
    - php
    - php-mysql
    - libapache2-mod-php
  tags:
    - delete-lamp