---
- name: "install apache"
  apt: name={{ item }}
  loop:
    - apache2
  tags:
    - apache-install
    - lamp-full-install
    - wp-lamp-full-install

- name: "enable apache rewrite"
  shell: a2enmod rewrite
  notify: Restart Apache
  tags:
    - apache-install
    - lamp-full-install
    - wp-lamp-full-install
    
- name: "create folder {{ app_domain }}"
  stat:
    path: "/var/www/{{ app_domain }}"
  register: appdomain
  tags:
    - lamp-full-install
    - lamp-create-single-app
    - wp-lamp-full-install

- name: "directory is already existed"
  debug:
    msg: "directory is already existed"
  when: appdomain.stat.exists
  tags:
    - lamp-full-install
    - lamp-create-single-app
    - wp-lamp-full-install

- name: "create folder {{ app_domain }}"
  file:
    path: "/var/www/{{ app_domain }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
  when: appdomain.stat.exists == false
  tags:
    - lamp-full-install
    - lamp-create-single-app
    - wp-lamp-full-install

- name: "set up apache virtualhost"
  template:
    src: "files/{{ item }}"
    dest: "/etc/apache2/sites-available/{{ app_config }}"
  with_items:
    - apache.conf.j2
  notify: Reload Apache
  tags:
    - lamp-full-install
    - lamp-create-single-app
    - wp-lamp-full-install

- name: "copy index.html"
  copy: 
    src: "{{ item }}"
    dest: "/var/www/{{ app_domain }}"
  with_items:
    - index.html
  tags:
    - lamp-full-install
    - lamp-create-single-app
    - wp-lamp-full-install

- name: "replace apache rewrite"
  # lineinfile:
  #   path: 
  #   regexp: '{{item.From}}'
  #   line: '{{item.To}}'
  replace:
    dest=/etc/apache2/apache2.conf regexp='AllowOverride None' replace='AllowOverride All'
  # with_items:
  #   - { From: 'AllowOverride None', To: '{{ rewrite }}'}
  notify: Restart Apache
  tags:
    - lamp-full-install
    - wp-lamp-full-install

- name: "enable new site"
  shell: /usr/sbin/a2ensite {{ app_config }}
  notify: Reload Apache
  tags:
    - lamp-full-install
    - lamp-create-single-app
    - wp-lamp-full-install

- name: "disable default apache site"
  shell: /usr/sbin/a2dissite 000-default.conf
  when: disable_default
  notify: Reload Apache
  tags:
    - lamp-full-install
    - wp-lamp-full-install

## Cleanup
- name: "Running command : check directory"
  stat:
    path: /var/www/{{ app_domain }}
  register: app_dir
  tags:
    - lamp-delete-single-app

- name: "Running command : delete directory"
  command: "rm -fr /var/www/{{ app_domain }}"
  when: app_dir.stat.exists
  args:
    warn: false
  tags:
    - lamp-delete-single-app

- name: "Running message : if directory doesn't exist"
  debug:
    msg: "directory is doesn't exist"
  when: app_dir.stat.exists == false
  tags:
    - lamp-delete-single-app

- name: "Running command : disable apache site"
  shell: "/usr/sbin/a2dissite {{ app_config }}"
  notify: Reload Apache
  tags:
    - lamp-delete-single-app

- name: "Running command : check directory"
  stat:
    path: /etc/apache2/sites-available/{{ app_config }}"
  register: app_apache_available
  tags:
    - lamp-delete-single-app

- name: "Running command : delete site"
  command: "rm /etc/apache2/sites-available/{{ app_config }}"
  notify: Reload Apache
  when: app_apache_available.stat.exists
  tags:
    - lamp-delete-single-app

- name: "Running message : if site-available doesn't exist"
  debug:
    msg: "directory is doesn't exist"
  when: app_apache_available.stat.exists == false
  tags:
    - lamp-delete-single-app

# Cleanup
- name: "Running command : uninstall LAMP"
  apt: name={{ item }} status=absent
  loop:
    - apache2
    - mysql-server
    - python3-pymysql
    - php7.4
    - php7.4-common
    - php7.4-mysql
    - libapache2-mod-php7.4
  tags:
    - lamp-full-uninstall

- name: "Uninstall Apache"
  apt: name={{ item }} status=absent
  loop:
    - apache2
  tags:
    - apache-uninstall
