---
- name: "Running command : install Apache"
  apt: name={{ item }}
  loop:
    - apache2
  tags:
    - apache

- name: "Running command : create document root"
  file:
    path: "/var/www/{{ app_domain }}"
    state: directory
    owner: "{{ app_username }}"
    mode: '0755'
  tags:
    - apache
    - create-app-apache

- name: "Running command : set up apache virtualhost"
  template:
    src: "files/{{ item }}"
    dest: "/etc/apache2/sites-available/{{ app_config }}"
  with_items:
    - apache.conf.j2
  notify: Reload Apache
  tags:
    - apache
    - create-app-apache

- name: "Running command : copy index.html"
  copy: 
    src: "{{ item }}"
    dest: "/var/www/{{ app_domain }}"
  with_items:
    - index.html
  tags:
    - apache
    - create-app-apache

- name: "Running command : enable new site"
  shell: /usr/sbin/a2ensite {{ app_config }}
  notify: Reload Apache
  tags:
    - apache
    - create-app-apache

- name: "Running command : disable default apache site"
  shell: /usr/sbin/a2dissite 000-default.conf
  when: disable_default
  notify: Reload Apache
  tags:
    - apache