---
- name: "install nginx"
  apt: name={{ item }}
  loop:
    - nginx
  tags:
    - nginx

- name: "create folder {{ app_domain }}"
  stat:
    path: "/var/www/{{ app_domain }}"
  register: appdomain
  tags:
    - nginx
    - create-app-nginx

- name: "directory is already existed"
  debug:
    msg: "directory is already existed"
  when: appdomain.stat.exists
  tags:
    - nginx
    - create-app-nginx

- name: "create folder {{ app_domain }}"
  file:
    path: "/var/www/{{ app_domain }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
  when: appdomain.stat.exists == false
  tags:
    - nginx
    - create-app-nginx

- name: "set up nginx virtualhost"
  template:
    src: "files/{{ item }}"
    dest: "/etc/nginx/sites-available/{{ app_config }}"
  with_items:
    - nginx.conf.j2
  notify: Reload Nginx
  tags:
    - nginx
    - create-app-nginx

- name: "copy index.html"
  copy: 
    src: "{{ item }}"
    dest: "/var/www/{{ app_domain }}"
  with_items:
    - index.html
  tags:
    - nginx
    - create-app-nginx

- name: "enable new site"
  file:
    src: "/etc/nginx/sites-available/{{ app_config }}"
    dest: "/etc/nginx/sites-enabled/{{ app_config }}"
    state: link
  notify: Reload Nginx
  tags:
    - nginx
    - create-app-nginx

- name: "disable default nginx site"
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  notify: Reload Nginx
  tags:
    - nginx