---
# CMS Manajer - Export DB
- name: "export database app"
  no_log: true
  mysql_db:
    name: "{{ app_database }}"
    state: dump
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"
    target: /home/cmsmanajer/database/{{ app_database }}.sql
  tags:
    - export-db
