---
- name: "install php modules"
  apt: name={{ item }}
  loop:
    - php7.4-curl
    - php7.4-gd
    - php7.4-mbstring
    - php7.4-xml
    - php7.4-xmlrpc
    - php7.4-soap
    - php7.4-intl
    - php7.4-zip
  tags:
    - wp-lamp-full-install
    - wp-lemp-full-install
     
- name: "set up apache virtualhost"
  template:
    src: "files/{{ item }}"
    dest: "/etc/apache2/sites-available/{{ app_config }}"
  with_items:
    - apache.conf.j2
  notify: Reload Apache
  tags:
    - wp-lamp-full-install
    - wp-lamp-create-single-app

- name: "set up nginx virtualhost"
  template:
    src: "files/{{ item }}"
    dest: "/etc/nginx/sites-available/{{ app_config }}"
  with_items:
    - nginx.conf.j2
  notify: Reload Nginx
  tags:
    - wp-lemp-full-install
    - wp-lemp-create-single-app

- name: "enable new site"
  shell: /usr/sbin/a2ensite {{ app_config }}
  notify: Reload Apache
  tags:
    - wp-lamp-full-install
    - wp-lamp-create-single-app

- name: "enable new site"
  file:
    src: "/etc/nginx/sites-available/{{ app_config }}"
    dest: "/etc/nginx/sites-enabled/{{ app_config }}"
    state: link
  notify: Reload Nginx
  tags:
    - wp-lemp-full-install
    - wp-lemp-create-single-app

- name: "disable default apache site"
  shell: /usr/sbin/a2dissite 000-default.conf
  when: disable_default
  notify: Reload Apache
  tags:
    - wp-lamp-full-install

- name: "disable default nginx site"
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  notify: Reload Nginx
  tags:
    - wp-lemp-full-install

- name: "create folder {{ app_domain }}"
  stat:
    path: "/var/www/{{ app_domain }}"
  register: wpapp
  tags:
    - wp-lamp-full-install
    - wp-lemp-full-install
    - wp-lemp-create-single-app
    - wp-lamp-create-single-app

- name: "directory is already existed"
  shell: "rm -fr /var/www/{{ app_domain }}"
  args:
    warn: false
  when: wpapp.stat.exists
  tags:
    - wp-lamp-full-install
    - wp-lemp-full-install
    - wp-lemp-create-single-app
    - wp-lamp-create-single-app

- name: Wait until deleted
  wait_for:
    path: "/var/www/{{ app_domain }}"
    state: absent
  tags:
    - wp-lemp-create-single-app 
    - wp-lamp-create-single-app

- name: "download and unpack latest WordPress"
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: "/var/www"
    remote_src: yes
    creates: "/var/www/wordpress"
    owner: www-data
    group: www-data
    mode: "755"
  tags:
    - wp-lamp-full-install
    - wp-lemp-full-install
    - wp-lemp-create-single-app
    - wp-lamp-create-single-app

- name: "rename wordpress folder"
  shell: "mv /var/www/wordpress /var/www/{{ app_domain }}"
  # when: wpapp.stat.exists == false
  # shell: "rsync -a /var/www/wordpress /var/www/{{ app_domain }}"
  tags:
    - wp-lamp-full-install
    - wp-lemp-full-install
    - wp-lemp-create-single-app
    - wp-lamp-create-single-app

- name: Wait until moved
  wait_for:
    path: "/var/www/{{ app_domain }}"
    state: present
  tags:
    - wp-lemp-create-single-app 
    - wp-lamp-create-single-app

- name: "configure wordpress"
  command: wp core config
            --allow-root
            --path="/var/www/{{ app_domain }}"
            --dbname="{{ app_database }}"
            --dbuser="{{ app_username }}"
            --dbpass="{{ app_password }}"
            --dbprefix="{{ app_dbprefix }}"
  tags:
    - wp-lamp-full-install
    - wp-lemp-full-install
    - wp-lemp-create-single-app
    - wp-lamp-create-single-app

- name: "install wordpress tables"
  command: wp core install
            --allow-root
            --path="/var/www/{{ app_domain }}"
            --url="{{ wordpress_home_url }}"
            --title="{{ wordpress_site_title }}"
            --admin_user="{{ wordpress_admin_user }}"
            --admin_password="{{ wordpress_admin_user_pass }}"
            --admin_email="{{ wordpress_admin_email }}"
  tags:
    - wp-lamp-full-install
    - wp-lemp-full-install
    - wp-lemp-create-single-app
    - wp-lamp-create-single-app

- name: "set ownership"
  file:
    path: "/var/www/{{ app_domain }}"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
    mode: "755"
  tags:
    - wp-lamp-full-install
    - wp-lemp-full-install
    - wp-lemp-create-single-app
    - wp-lamp-create-single-app

- name: "set permissions for directories"
  shell: "/usr/bin/find /var/www/{{ app_domain }}/ -type d -exec chmod 755 {} \\;"
  tags:
    - wp-lamp-full-install
    - wp-lemp-full-install
    - wp-lemp-create-single-app
    - wp-lamp-create-single-app

- name: "set permissions for files"
  shell: "/usr/bin/find /var/www/{{ app_domain }}/ -type f -exec chmod 640 {} \\;"
  notify: Reload Apache
  tags:
    - wp-lamp-full-install
    - wp-lamp-create-single-app

- name: "set permissions for files"
  shell: "/usr/bin/find /var/www/{{ app_domain }}/ -type f -exec chmod 640 {} \\;"
  notify: Reload Nginx
  tags:
    - wp-lemp-full-install
    - wp-lemp-create-single-app