---
- name: "Running command : install PHP Extensions"
  apt: name={{ item }}
  # loop: "{{ php_modules }}"
  loop:
    - php-curl
    - php-gd
    - php-mbstring
    - php-xml
    - php-xmlrpc
    - php-soap
    - php-intl
    - php-zip
  tags:
    - apache
    - nginx
  
- name: "Running command : set up apache virtualhost"
  template:
    src: "files/{{ item }}"
    dest: "/etc/apache2/sites-available/{{ app_config }}"
  with_items:
    - apache.conf.j2
  notify: Reload Apache
  tags:
    - apache
    - create-app-wp-apache

- name: "Running command : set up nginx virtualhost"
  template:
    src: "files/{{ item }}"
    dest: "/etc/nginx/sites-available/{{ app_config }}"
  with_items:
    - nginx.conf.j2
  notify: Reload Nginx
  tags:
    - nginx
    - create-app-wp-nginx

- name: "Running command : enable new site"
  shell: /usr/sbin/a2ensite {{ app_config }}
  notify: Reload Apache
  tags:
    - apache
    - create-app-wp-apache

- name: "Running command : enable new site"
  file:
    src: "/etc/nginx/sites-available/{{ app_config }}"
    dest: "/etc/nginx/sites-enabled/{{ app_config }}"
    state: link
  notify: Reload Nginx
  tags:
    - nginx
    - create-app-wp-nginx

- name: "Running command : disable default apache site"
  shell: /usr/sbin/a2dissite 000-default.conf
  when: disable_default
  notify: Reload Apache
  tags:
    - apache

- name: "Running command : disable default nginx site"
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  notify: Reload Nginx
  tags:
    - nginx

- name: "Running command : sets the root password"
  mysql_user:
    name: "{{ mysql_root_username }}"
    password: "{{ mysql_root_password }}"
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  tags:
    - apache
    - nginx

- name: "Running command : removes all anonymous user accounts"
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"
  tags:
    - apache
    - nginx

- name: "Running command : removes the test database"
  mysql_db:
    name: test
    state: absent
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"
  tags:
    - apache
    - nginx

- name: "Running command : check if wp-cli exists"
  stat: path="/usr/bin/wp"
  register: wpcli_exist
  tags:
    - apache
    - nginx
    - create-app-wp-nginx
    - create-app-wp-apache

- name: "Running command : updating wp-cli"
  shell: "/usr/bin/wp cli update --yes"
  when: wpcli_exist.stat.exists
  tags:
    - apache
    - nginx
    - create-app-wp-nginx
    - create-app-wp-apache

- name: "Running command : install wp-cli"
  get_url:
    url="https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar"
    dest="/usr/bin/wp"
    force_basic_auth=yes
    mode=0755
  when: not wpcli_exist.stat.exists
  tags:
    - apache
    - nginx
    - create-app-wp-nginx
    - create-app-wp-apache

- name: "Running command : download and unpack latest WordPress"
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: "/var/www"
    remote_src: yes
    creates: "/var/www/wordpress"
  tags:
    - apache
    - nginx
    - create-app-wp-nginx
    - create-app-wp-apache

- name: "Running command : rename wordpress folder"
  shell: "mv /var/www/wordpress /var/www/{{ app_domain }}"
  tags:
    - apache
    - nginx
    - create-app-wp-nginx
    - create-app-wp-apache

# - name: Configure WordPress
#   # become: "{{ app_username }}"
#   command: wp core download
#             --allow-root
#             --path="/var/www/{{ app_domain }}"

- name: Configure WordPress
  command: wp core config
            --allow-root
            --path="/var/www/{{ app_domain }}"
            --dbname="{{ app_database }}"
            --dbuser="{{ app_username }}"
            --dbpass="{{ app_password }}"
            --dbprefix="{{ app_dbprefix }}"
  tags:
    - apache
    - nginx
    - create-app-wp-nginx
    - create-app-wp-apache

# - name: "Running command : setup wp-config.php"
#   template:
#     src: "files/{{ item }}"
#     dest: "/var/www/{{ app_domain }}/wp-config.php"
#   with_items:
#     - wp-config.php.j2

- name: "Running command : install WordPress tables"
  command: wp core install
            --allow-root
            --path="/var/www/{{ app_domain }}"
            --url="{{ wordpress_home_url }}"
            --title="{{ wordpress_site_title }}"
            --admin_user="{{ wordpress_admin_user }}"
            --admin_password="{{ wordpress_admin_user_pass }}"
            --admin_email="{{ wordpress_admin_email }}"
  tags:
    - apache
    - nginx
    - create-app-wp-nginx
    - create-app-wp-apache

- name: "Running command : set ownership"
  file:
    path: "/var/www/{{ app_domain }}"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
  tags:
    - apache
    - nginx
    - create-app-wp-nginx
    - create-app-wp-apache

- name: "Running command : set permissions for directories"
  shell: "/usr/bin/find /var/www/{{ app_domain }}/ -type d -exec chmod 750 {} \\;"
  tags:
    - apache
    - nginx
    - create-app-wp-nginx
    - create-app-wp-apache

- name: "Running command : set permissions for files"
  shell: "/usr/bin/find /var/www/{{ app_domain }}/ -type f -exec chmod 640 {} \\;"
  notify: Reload Apache
  tags:
    - apache
    - create-app-wp-apache

- name: "Running command : set permissions for files"
  shell: "/usr/bin/find /var/www/{{ app_domain }}/ -type f -exec chmod 640 {} \\;"
  notify: Reload Nginx
  tags:
  - nginx
  - create-app-wp-nginx