---
- name: "add gpg docker"
  apt_key:
    url: "{{ docker_apt_gpg_key }}"
    state: present
  tags:
    - docker-install

- name: "add docker repository"
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true
  tags:
    - docker-install

- name: "install docker"
  apt: name={{ item }} update_cache=false
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  tags:
    - docker-install

- name: "start systemd docker"
  systemd:
    state: started
    name: docker
    enabled: true
  tags:
    - docker-install

- name: "check current docker-compose version"
  command: docker-compose --version
  register: docker_compose_vsn
  changed_when: false
  failed_when: false
  check_mode: no
  tags:
    - docker-install

- set_fact:
    docker_compose_current_version: "{{ docker_compose_vsn.stdout | regex_search('(\\d+(\\.\\d+)+)') }}"
  when:
    - docker_compose_vsn.stdout is defined
  tags:
    - docker-install

- name: "install or upgrade docker-compose"
  get_url: 
    url : "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: 'a+x'
    force: yes
  when: >
    docker_compose_current_version is not defined
    or docker_compose_current_version is version(docker_compose_version, '<')
  tags:
    - docker-install

# Cleanup
- name: "add docker repository"
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true
  tags:
    - docker-uninstall

- name: "uninstall docker"
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker*
    state: absent
    update_cache: false
  notify: Autoremove
  tags:
    - docker-uninstall

- name: "check docker-compose"
  stat:
    path: /usr/local/bin/docker-compose
  register: app_dir
  tags:
    - docker-uninstall

- name: "delete docker-compose"
  shell: "rm /usr/local/bin/docker-compose"
  when: app_dir.stat.exists
  args:
    warn: false
  tags:
    - docker-uninstall

- name: "if docker-compose doesn't exist"
  debug:
    msg: "docker-compose is doesn't exist"
  when: app_dir.stat.exists == false
  tags:
    - docker-uninstall
