---
- name: "install php for apache"
  apt: name={{ item }}
  loop:
    - php
    - php-mysql
    - libapache2-mod-php
  tags: 
    - apache

- name: "install php for nginx"
  apt: name={{ item }}
  loop:
    - php
    - php-fpm
    - php-mysql
  tags: 
    - nginx

- name: "copy info.php"
  copy: 
    src: "{{ item }}"
    dest: "/var/www/{{ app_domain }}"
  with_items:
    - info.php
  tags:
    - apache
    - nginx