---
- name : vars
  include_vars :
    dir: vars
    files_matching: default.yml

- name: "Running command : install LAMP"
  apt: name={{ item }}
  loop:
    - apache2
    - mysql-server
    - python3-pymysql
    - php
    - php-mysql
    - libapache2-mod-php

- name: "Running command : create document root"
  file:
    path: "/var/www/{{ app_domain }}"
    state: directory
    owner: "{{ app_username }}"
    mode: '0755'

- name: "Running command : set up apache virtualhost"
  template:
    src: "files/{{ item }}"
    dest: "/etc/apache2/sites-available/{{ app_config }}"
  with_items:
    - apache.conf.j2
  notify: Reload Apache

- name: "Running command : copy index.html and info.php"
  copy: 
    src: "{{ item }}"
    dest: "/var/www/{{ app_domain }}"
  with_items:
    - index.html
    - info.php

- name: "Running command : enable new site"
  shell: /usr/sbin/a2ensite {{ app_config }}
  notify: Reload Apache

- name: "Running command : disable default apache site"
  shell: /usr/sbin/a2dissite 000-default.conf
  when: disable_default
  notify: Reload Apache

- name: "Running command : sets the root password"
  no_log: true
  mysql_user:
    name: "{{ mysql_root_username }}"
    password: "{{ mysql_root_password }}"
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: "Running command : removes all anonymous user accounts"
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"

- name: "Running command : removes the test database"
  mysql_db:
    name: test
    state: absent
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"