---
- name: "Running command : update and upgrade systems"
  apt:
    update_cache: yes
    upgrade: dist
    autoremove: yes

- name: "Running command : install systems dependencies"
  apt:
    name: 
      - git
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - zip
      - unzip
      - build-essential
      - ncdu
      - htop
      - net-tools
      - vim
      - ufw
    state: present