---
- name : vars
  include_vars :
    dir: vars
    files_matching: default.yml

- name: "Running command : install LEMP"
  apt: name={{ item }}
  loop:
    - nginx
    - mysql-server
    - python3-pymysql
    - php
    - php-fpm
    - php-mysql
    
- name: "Running command : create document root"
  file:
    path: "/var/www/{{ app_domain }}"
    state: directory
    owner: "{{ app_username }}"
    mode: '0755'

- name: "Running command : set up nginx virtualhost"
  template:
    src: "files/{{ item }}"
    dest: "/etc/nginx/sites-available/{{ app_config }}"
  with_items:
    - nginx.conf.j2
  notify: Reload Nginx

- name: "Running command : copy index.html and info.php"
  copy: 
    src: "{{ item }}"
    dest: "/var/www/{{ app_domain }}"
  with_items:
    - index.html
    - info.php

- name: "Running command : enable new site"
  file:
    src: "/etc/nginx/sites-available/{{ app_config }}"
    dest: "/etc/nginx/sites-enabled/{{ app_config }}"
    state: link
  notify: Reload Nginx

- name: "Running command : disable default nginx site"
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  notify: Reload Nginx

- name: "Running command : sets the root password"
  no_log: true
  mysql_user:
    name: "{{ mysql_root_username }}"
    password: "{{ mysql_root_password }}"
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: "Running command : removes all anonymous user accounts"
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"

- name: "Running command : removes the test database"
  mysql_db:
    name: test
    state: absent
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"