---
- name: "install mysql"
  apt: name={{ item }}
  loop:
    - mysql-server
    - python3-pymysql
  tags:
    - apache
    - nginx

- name: "sets the root password"
  no_log: true
  mysql_user:
    name: "{{ mysql_root_username }}"
    password: "{{ mysql_root_password }}"
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  tags:
    - apache
    - nginx

- name: "removes all anonymous user accounts"
  no_log: true
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"
  tags:
    - apache
    - nginx

- name: "removes the test database"
  mysql_db:
    name: test
    state: absent
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"
  tags:
    - apache
    - nginx

- name: "creates database for App"
  no_log: true
  mysql_db:
    name: "{{ app_database }}"
    state: present
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"
  tags:
    - create-database
    - create-app-wp-nginx
    - create-app-wp-apache

- name: "create database user for App"
  no_log: true
  mysql_user:
    name: "{{ app_username }}"
    password: "{{ app_password }}"
    priv: "{{ app_database }}.*:ALL"
    state: present
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"
  tags:
    - create-database
    - create-app-wp-nginx
    - create-app-wp-apache

# Cleanup
- name: "Running command : delete database for App"
  no_log: true
  mysql_db:
    name: "{{ app_database }}"
    state: absent
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"
  tags:
    - delete-mysql-database

- name: "Running command : delete database user for App"
  no_log: true
  mysql_user:
    name: "{{ app_username }}"
    password: "{{ app_password }}"
    priv: "{{ app_database }}.*:ALL"
    state: absent
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"
  tags:
    - delete-mysql-database