---
- name : vars
  include_vars :
    dir: vars
    files_matching: default.yml

- name: "Running command : create document root"
  file:
    path: "/var/www/{{ app_domain }}"
    state: directory
    owner: "{{ app_username }}"
    mode: '0755'

- name: "Running command : set up apache virtualhost"
  template:
    src: "files/{{ item }}"
    dest: "/etc/apache2/sites-available/{{ app_config }}"
  with_items:
    - apache.conf.j2
  notify: Reload Apache

- name: "Running command : copy index.html and info.php"
  copy: 
    src: "{{ item }}"
    dest: "/var/www/{{ app_domain }}"
  with_items:
    - index.html
    - info.php

- name: "Running command : enable new site"
  shell: /usr/sbin/a2ensite {{ app_config }}
  notify: Reload Apache

- name: "Running command : disable default apache site"
  shell: /usr/sbin/a2dissite 000-default.conf
  when: disable_default
  notify: Reload Apache