---
- name: "add mongo ppa key"      
  shell: wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
  args:
    warn: false
  tags:
    - mongodb-install

- name: "add mongo sources list  "    
  shell: echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/{{ ansible_distribution | lower }} {{ ansible_distribution_release }}/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
  tags:
    - mongodb-install

- name: "update cache repository"      
  apt: 
    update_cache: yes
  tags:
    - mongodb-install

- name: "install mongodb"      
  apt: name={{ item }} state=present
  loop: 
    - mongodb-org 
  tags:
    - mongodb-install

- name: "start systemd mongod"
  systemd:
    state: started
    name: mongod
    enabled: yes
  tags:
    - mongodb-install

# Cleanup
- name: "check mongodb repository"
  stat:
    path: /etc/apt/sources.list.d/mongodb-org-4.4.list
  register: app_dir
  tags:
    - mongodb-uninstall

- name: "delete mongodb sources list"    
  shell: "rm /etc/apt/sources.list.d/mongodb-org-4.4.list"
  when: app_dir.stat.exists
  args:
    warn: false
  tags:
    - mongodb-uninstall

- name: "if mongodb doesn't exist"
  debug:
    msg: "mongodb is doesn't exist"
  when: app_dir.stat.exists == false
  tags:
    - mongodb-uninstall

- name: "update cache repository"      
  apt: 
    update_cache: yes
  tags:
    - mongodb-uninstall

- name: "install mongodb"      
  apt: 
    name: mongodb-org 
    state: absent 
  tags:
    - mongodb-uninstall