---
- name: "create user '{{ username }}'"
  user:
    name: "{{ username }}"
    password: "{{ password }}"
    groups: sudo
    state: present
    shell: /bin/bash
    system: no
    createhome: yes
    home: "/home/{{ username }}"

- name: "replace sshd_config for pass auth"
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '{{item.From}}'
    line: '{{item.To}}'
  with_items:
    - { From: 'PasswordAuthentication no', To: '{{pass_auth}}'}

- name: "replace sshd_config for pubkey auth"
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '{{item.From}}'
    line: '{{item.To}}'
  with_items:
    - { From: 'PubkeyAuthentication no', To: '{{pubkey_auth}}'}

- name: "reload sshd service"
  systemd:
    state: restarted
    name: sshd